// Generated by CoffeeScript 1.3.3
(function() {
  var formidable, fs, querystring, show, start, upload;

  formidable = require('formidable');

  fs = require('fs');

  querystring = require('querystring');

  start = function(response) {
    var body;
    console.log("request handler 'start' was called.");
    body = "<html>\n  <head>\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n  </head>\n  <body>\n    <form action=\"/upload\" enctype=\"multipart/form-data\" method=\"post\">\n      <input type=\"file\" name=\"upload\" multiple=\"multiple\" />\n      <input type=\"submit\" value=\"Upload PNG\" />\n    </form>\n  </body>\n</html>";
    response.writeHead(200, {
      'Content-Type': 'text/html'
    });
    response.write(body);
    return response.end();
  };

  upload = function(response, request) {
    var form;
    console.log("request handler 'upload' was called.");
    form = new formidable.IncomingForm();
    console.log('about to parse');
    form.parse(request, function(error, fields, files) {
      console.log('parsing done');
      return fs.rename(files.upload.path, '/tmp/test.png', function(err) {
        if (err) {
          fs.unlink('/tmp/test.png');
          return fs.rename(files.upload.path, '/tmp/test.png');
        }
      });
    });
    response.writeHead(200, {
      'Content-Type': 'text/html'
    });
    response.write('received image:<br />');
    response.write('<img src="/show" >');
    return response.end();
  };

  show = function(response) {
    console.log("Request handler 'show' was called.");
    return fs.readFile("/tmp/test.png", "binary", function(error, file) {
      if (error) {
        response.writeHead(500, {
          'Content-Type': 'text/plain'
        });
        response.write(error + '\n');
        return response.end();
      } else {
        response.writeHead(200, {
          'Content-Type': 'image/png'
        });
        response.write(file, 'binary');
        return response.end();
      }
    });
  };

  exports.start = start;

  exports.upload = upload;

  exports.show = show;

}).call(this);
