// Generated by CoffeeScript 1.3.3
(function() {
  var querystring, start, upload;

  querystring = require('querystring');

  start = function(response, postData) {
    var body;
    console.log("request handler 'start' was called.");
    body = "<html>\n  <head>\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n  </head>\n  <body>\n    <form action=\"/upload\" method=\"post\">\n      <textarea name=\"text\" rows=\"20\" cols=\"60\"></textarea>\n      <input type=\"submit\" value=\"Submit text\" />\n    </form>\n  </body>\n</html>";
    response.writeHead(200, {
      'Content-Type': 'text/html'
    });
    response.write(body);
    return response.end();
  };

  upload = function(response, postData) {
    console.log("request handler 'upload' was called.");
    response.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    response.write("You've sent the text: " + (querystring.parse(postData).text));
    return response.end();
  };

  exports.start = start;

  exports.upload = upload;

}).call(this);
