// Generated by CoffeeScript 1.3.3
(function() {
  var exec, start, upload;

  exec = require('child_process').exec;

  start = function(response) {
    console.log("request handler 'start' was called.");
    return exec('ls -lah', function(error, stdout, stderr) {
      response.writeHead(200, {
        'Content-Type': 'text/plain'
      });
      response.write(stdout);
      return response.end();
    });
  };

  upload = function(response) {
    console.log("request handler 'upload' was called.");
    response.writeHead(200, {
      'Content-Type': 'text/plain'
    });
    response.write('hello upload');
    return response.end();
  };

  exports.start = start;

  exports.upload = upload;

}).call(this);
