// Generated by CoffeeScript 1.3.3
(function() {
  var route;

  route = function(handle, pathname, response, request) {
    console.log("About to route " + pathname);
    if (typeof handle[pathname] === "function") {
      return handle[pathname](response, request);
    } else {
      console.log("No request handler found for " + pathname);
      response.writeHead(404, {
        "Content-Type": "text/plain"
      });
      response.write("404 Not Found");
      return response.end();
    }
  };

  exports.route = route;

}).call(this);
