// Generated by CoffeeScript 1.3.3
(function() {
  var http, start, url;

  http = require('http');

  url = require('url');

  start = function(route, handle) {
    var onRequest;
    onRequest = function(request, response) {
      var pathname;
      pathname = url.parse(request.url).pathname;
      console.log("Request for " + pathname + " received");
      return route(handle, pathname, response);
    };
    http.createServer(onRequest).listen(8888);
    return console.log('server has started');
  };

  exports.start = start;

}).call(this);
